"""Versioned chat template for FramerAI instruction and tool-calling format."""

import json
from typing import Any

import torch


def _json_str(value: Any) -> str:
    """Render a tool payload as compact JSON, or as its own text if it is not JSON."""
    if isinstance(value, (dict, list)):
        return json.dumps(value)
    if isinstance(value, str):
        try:
            return json.dumps(json.loads(value))
        except Exception:
            return value
    return str(value)


class ChatTemplate:
    """Versioned Chat Template for SFT, DPO, and inference.

    Formats conversations into structured role segments:
    - system:     <system>...
    - user:       <user>...
    - reasoning:  <reasoning>...</reasoning>  (v2)
    - assistant:  <assistant>...
    - tool_call:  <tool_call>...
    - tool:       <tool>...
    """

    VERSION = "v2"
    SUPPORTED_VERSIONS = ("v1", "v2")

    CONTROL_MARKERS = {
        "<system>",
        "<user>",
        "<assistant>",
        "<reasoning>",
        "</reasoning>",
        "<tool>",
        "<tool_call>",
    }

    @property
    def special_tokens(self) -> set[str]:
        """Special/control tokens explicitly generated by this chat template."""
        if self.version == "v2":
            return set(self.CONTROL_MARKERS)
        return {m for m in self.CONTROL_MARKERS if m not in ("<reasoning>", "</reasoning>")}

    @property
    def allowed_special(self) -> set[str]:
        """Allowed special tokens when encoding chat template output."""
        return self.special_tokens

    def __init__(self, version: str = "v1"):
        if version not in self.SUPPORTED_VERSIONS:
            supported = ", ".join(repr(v) for v in self.SUPPORTED_VERSIONS)
            raise ValueError(f"Unsupported ChatTemplate version: {version!r}. Supported: {supported}")
        self.version = version

    def format_messages(self, messages: list[dict[str, Any]], add_generation_prompt: bool = False) -> str:
        """Format a list of message dicts into a single prompt string."""
        formatted_parts = []
        for msg in messages:
            role = msg.get("role", "").lower()
            content = msg.get("content", "")
            content_str = str(content).strip() if content is not None else ""

            if role == "system":
                formatted_parts.append(f"<system>{content_str}")
            elif role == "user":
                formatted_parts.append(f"<user>{content_str}")
            elif role == "reasoning" and self.version == "v2":
                formatted_parts.append(f"<reasoning>{content_str}</reasoning>")
            elif role == "assistant":
                if "tool_calls" in msg and msg["tool_calls"]:
                    tc = msg["tool_calls"]
                    if isinstance(tc, (dict, list)):
                        tc_str = json.dumps(tc)
                    elif isinstance(tc, str):
                        try:
                            parsed = json.loads(tc)
                            tc_str = json.dumps(parsed)
                        except Exception:
                            tc_str = tc
                    else:
                        tc_str = str(tc)
                    formatted_parts.append(f"<tool_call>{tc_str}</tool_call>")
                else:
                    formatted_parts.append(f"<assistant>{content_str}")
            elif role == "tool_call":
                if isinstance(content, (dict, list)):
                    c_str = json.dumps(content)
                elif isinstance(content, str):
                    try:
                        parsed = json.loads(content)
                        c_str = json.dumps(parsed)
                    except Exception:
                        c_str = content
                else:
                    c_str = str(content)
                formatted_parts.append(f"<tool_call>{c_str}</tool_call>")
            elif role in ("tool", "tool_result"):
                name = msg.get("name", "")
                prefix = f"[{name}] " if name else ""
                formatted_parts.append(f"<tool>{prefix}{content_str}")
            else:
                formatted_parts.append(f"<{role}>{content_str}")

        text = "".join(formatted_parts)
        if add_generation_prompt and not text.endswith("<assistant>"):
            text += "<assistant>"
        return text

    def _turn_ids(
        self,
        msg: dict[str, Any],
        tokenizer,
        content_allowed: set[str] | list[str] | str | None = None,
        target_reasoning: bool = True,
        target_assistant: bool = True,
    ) -> tuple[list[int], bool]:
        """Encode one message to ids, and say whether it is a training target.

        The markers are encoded separately from the content and only they are
        allowed to become control ids. That separation is the whole point: once
        a turn is flattened to a string the two are indistinguishable, and
        allowing the markers back would allow every marker the user typed too.
        """
        role = msg.get("role", "").lower()
        content = msg.get("content", "")
        content_str = str(content).strip() if content is not None else ""
        msg_target = msg.get("target")

        template_allowed = self.allowed_special
        turn_ids: list[int] = []

        def marker(text: str, allowed=None) -> None:
            turn_ids.extend(
                tokenizer.encode(
                    text,
                    add_special=False,
                    allowed_special=template_allowed if allowed is None else allowed,
                )
            )

        def body(text: str) -> None:
            if text:
                turn_ids.extend(
                    tokenizer.encode(text, add_special=False, allowed_special=content_allowed)
                )

        if role == "system":
            marker("<system>")
            body(content_str)
            is_target = bool(msg_target) if msg_target is not None else False
        elif role == "user":
            marker("<user>")
            body(content_str)
            is_target = bool(msg_target) if msg_target is not None else False
        elif role == "reasoning" and self.version == "v2":
            marker("<reasoning>")
            body(content_str)
            marker("</reasoning>")
            is_target = bool(msg_target) if msg_target is not None else target_reasoning
        elif role == "assistant":
            if "tool_calls" in msg and msg["tool_calls"]:
                marker("<tool_call>")
                body(_json_str(msg["tool_calls"]))
                marker("</tool_call>")
            else:
                marker("<assistant>")
                body(content_str)
            is_target = bool(msg_target) if msg_target is not None else target_assistant
        elif role == "tool_call":
            marker("<tool_call>")
            body(_json_str(content))
            marker("</tool_call>")
            is_target = bool(msg_target) if msg_target is not None else target_assistant
        elif role in ("tool", "tool_result"):
            name = msg.get("name", "")
            prefix = f"[{name}] " if name else ""
            marker("<tool>")
            body(f"{prefix}{content_str}")
            is_target = bool(msg_target) if msg_target is not None else False
        else:
            tag = f"<{role}>"
            marker(tag, allowed={tag} if tag in tokenizer.marker_tokens else None)
            body(content_str)
            is_target = bool(msg_target) if msg_target is not None else False

        return turn_ids, is_target

    def encode_prompt(
        self,
        messages: list[dict[str, Any]],
        tokenizer,
        add_generation_prompt: bool = True,
        allowed_special: set[str] | list[str] | str | None = None,
    ) -> list[int]:
        """Encode a conversation to prompt ids for inference.

        ``format_messages`` is for reading and for callers that want the text.
        Generation takes these ids instead, because the round trip through a
        string is lossy in the one way that matters: a re-encode cannot tell
        the ``<assistant>`` this template wrote from the one that arrived
        inside a message, so it either drops both boundaries or forges one.
        """
        ids: list[int] = []
        for msg in messages:
            turn_ids, _ = self._turn_ids(msg, tokenizer, content_allowed=allowed_special)
            ids.extend(turn_ids)

        if add_generation_prompt:
            opener = tokenizer.encode(
                "<assistant>", add_special=False, allowed_special=self.allowed_special
            )
            if ids[-len(opener):] != opener:
                ids.extend(opener)
        return ids

    def encode_conversation(
        self,
        messages: list[dict[str, Any]],
        tokenizer,
        max_len: int = 512,
        pad_to_max: bool = True,
        target_reasoning: bool = True,
        target_assistant: bool = True,
        allowed_special: set[str] | list[str] | str | None = None,
    ) -> dict[str, torch.Tensor]:
        """Encode a multi-turn conversation into input_ids and masked labels for SFT.

        Labels are pre-shifted for next-token prediction:
        input_ids = full_sequence[:-1]
        labels = full_sequence[1:] (with non-target positions set to -100)

        Reasoning and assistant turns can be independently targeted or masked.
        """
        full_tokens = [tokenizer.sos_id]
        full_is_target = [False]

        for msg in messages:
            turn_ids, is_target = self._turn_ids(
                msg,
                tokenizer,
                content_allowed=allowed_special,
                target_reasoning=target_reasoning,
                target_assistant=target_assistant,
            )
            full_tokens.extend(turn_ids)
            full_is_target.extend([is_target] * len(turn_ids))

        full_tokens.append(tokenizer.eos_id)
        full_is_target.append(full_is_target[-1] if full_is_target else False)

        input_ids = full_tokens[:-1]
        raw_labels = full_tokens[1:]
        target_mask = full_is_target[1:]

        labels = [tok if target else -100 for tok, target in zip(raw_labels, target_mask, strict=False)]

        if len(input_ids) > max_len:
            input_ids = input_ids[-max_len:]
            labels = labels[-max_len:]
            attention_mask = [1] * max_len
        elif pad_to_max and len(input_ids) < max_len:
            seq_len = len(input_ids)
            pad_len = max_len - seq_len
            input_ids.extend([tokenizer.pad_id] * pad_len)
            labels.extend([-100] * pad_len)
            attention_mask = [1] * seq_len + [0] * pad_len
        else:
            attention_mask = [1] * len(input_ids)

        return {
            "input_ids": torch.tensor(input_ids, dtype=torch.long),
            "labels": torch.tensor(labels, dtype=torch.long),
            "attention_mask": torch.tensor(attention_mask, dtype=torch.long),
        }
