/**
 * Model service.
 *
 * Routes each request to the FramerAI Python inference worker when a trained
 * checkpoint is available (see pythonBridge). When the model is disabled or the
 * worker is unavailable, it returns placeholder responses so the backend still
 * runs end to end without trained weights.
 */

const { randomUUID } = require("node:crypto");
const bridge = require("./pythonBridge");
const { logger } = require("./logger");

const GENERATED_URL = "/uploads/generated";

/**
 * Detect the intent/type of a user message.
 */
function detectIntent(content) {
  const lower = content.toLowerCase();
  if (
    lower.includes("generate image") ||
    lower.includes("create image") ||
    lower.includes("draw") ||
    lower.includes("picture of")
  ) {
    return "image";
  }
  if (
    lower.includes("generate video") ||
    lower.includes("create video") ||
    lower.includes("animate") ||
    lower.includes("video of")
  ) {
    return "video";
  }
  if (
    lower.includes("generate audio") ||
    lower.includes("text to speech") ||
    lower.includes("speak") ||
    lower.includes("say ") ||
    lower.includes("voice") ||
    lower.includes("sound of")
  ) {
    return "audio";
  }
  if (
    lower.includes("write code") ||
    lower.includes("implement") ||
    lower.includes("function") ||
    lower.includes("```") ||
    lower.includes("code for") ||
    lower.includes("program")
  ) {
    return "code";
  }
  return "text";
}

/**
 * Generate a code response based on the prompt.
 */
function generateCodeResponse(prompt) {
  const lower = prompt.toLowerCase();

  if (lower.includes("fibonacci")) {
    return `\`\`\`python
def fibonacci(n):
    """Generate the nth Fibonacci number."""
    if n <= 0:
        return 0
    elif n == 1:
        return 1

    a, b = 0, 1
    for _ in range(2, n + 1):
        a, b = b, a + b
    return b


# Example usage
for i in range(10):
    print(f"F({i}) = {fibonacci(i)}")
\`\`\``;
  }

  if (lower.includes("sort") || lower.includes("sorting")) {
    return `\`\`\`python
def quicksort(arr):
    """Quicksort implementation."""
    if len(arr) <= 1:
        return arr

    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]

    return quicksort(left) + middle + quicksort(right)


# Example
data = [64, 34, 25, 12, 22, 11, 90]
print(f"Sorted: {quicksort(data)}")
\`\`\``;
  }

  if (lower.includes("api") || lower.includes("server") || lower.includes("express")) {
    return `\`\`\`javascript
const express = require('express');
const app = express();

app.use(express.json());

const items = [];

app.get('/api/items', (req, res) => {
  res.json(items);
});

app.post('/api/items', (req, res) => {
  const item = { id: Date.now(), ...req.body };
  items.push(item);
  res.status(201).json(item);
});

app.listen(3000, () => {
  console.log('Server running on port 3000');
});
\`\`\``;
  }

  return `\`\`\`python
# FramerAI Generated Code
# Prompt: ${prompt}

def solution():
    """Generated solution based on the prompt."""
    # Implementation would be generated by the trained model
    pass

if __name__ == "__main__":
    solution()
\`\`\``;
}

/**
 * Canonical cognition-trace schema.
 *
 * A trace is only forwarded when it is structurally valid AND the request
 * context permits it (privacy requirement: recalled memories may contain
 * earlier user content, so traces are gated behind INCLUDE_TRACE or an
 * operator-context header).
 *
 * Shape: {
 *   memories?:   Array<{ text: string, score: number }>,
 *   affect?:     Array<number>,               // affective vector
 *   affect_adj?: number,                       // sampling temperature adjustment
 *   sampling?:   Record<string, number>,       // top-k, top-p, etc.
 *   tools?:      Array<{ name, input, output }>,
 * }
 */
function validateTrace(trace) {
  if (!trace || typeof trace !== "object" || Array.isArray(trace)) return null;

  const cleaned = {};
  let hasContent = false;

  if (Array.isArray(trace.memories) && trace.memories.length > 0) {
    cleaned.memories = trace.memories.map((m) => ({
      text: String(m?.text ?? ""),
      score: Number(m?.score) || 0,
    }));
    hasContent = true;
  }

  if (Array.isArray(trace.affect) && trace.affect.length > 0) {
    cleaned.affect = trace.affect.map((v) => Number(v) || 0);
    hasContent = true;
  }

  if (trace.affect_adj != null && !isNaN(Number(trace.affect_adj))) {
    cleaned.affect_adj = Number(trace.affect_adj);
    hasContent = true;
  }

  if (trace.sampling && typeof trace.sampling === "object" && !Array.isArray(trace.sampling)) {
    const samplingEntries = Object.entries(trace.sampling).map(([k, v]) => [k, Number(v) || 0]);
    if (samplingEntries.length > 0) {
      cleaned.sampling = Object.fromEntries(samplingEntries);
      hasContent = true;
    }
  }

  if (Array.isArray(trace.tools) && trace.tools.length > 0) {
    cleaned.tools = trace.tools;
    hasContent = true;
  }

  // Return null if trace is empty (no meaningful content)
  return hasContent ? cleaned : null;
}

/**
 * Returns true when the caller context allows cognition traces to be forwarded.
 * Traces contain recalled memories which may include earlier user content, so
 * they are only sent when explicitly opted in.
 *
 * @param {object|null} operatorContext - headers or flags from the caller
 */
function traceAllowed(operatorContext) {
  if (process.env.INCLUDE_TRACE === "true") return true;
  if (operatorContext?.operator === true) return true;
  return false;
}

async function processMessage(messages, requestType = "text", settings = {}, requestId = null, operatorCtx = null) {
  const lastMessage = messages[messages.length - 1];
  const content = lastMessage.content;
  const intent = requestType !== "text" ? requestType : detectIntent(content);

  if (bridge.available()) {
    try {
      return await modelChat(intent, content, settings, requestId, operatorCtx);
    } catch (err) {
      logger.warn("falling back to placeholder", { error: err.message, requestId });
    }
  }

  return mockChat(intent, content, messages);
}

async function modelChat(intent, content, settings = {}, requestId = null, operatorCtx = null) {
  if (intent === "image" || intent === "video" || intent === "audio") {
    const result = await bridge.request(intent, { prompt: content, ...settings }, requestId);
    return {
      type: intent,
      content: `Here is the ${intent} generated for: "${content}"`,
      metadata: { prompt: content, url: `${GENERATED_URL}/${result.file}`, model: `framerai-${intent}` },
    };
  }

  const op = intent === "code" ? "code" : "chat";
  const result = await bridge.request(op, { prompt: content, ...settings }, requestId);
  const metadata = { model: `framerai-${intent === "code" ? "code" : "text"}` };
  // Tool steps travel with the reply so the UI can show what was searched and
  // read instead of presenting a sourced answer as if it came from the weights.
  if (result.tools) metadata.tools = result.tools;
  // Cognition trace — only forwarded when the operator context permits it
  // (privacy: recalled memories may contain earlier user content).
  // Strip it from the result if not allowed, even if Python sent it.
  if (result.trace) {
    if (traceAllowed(operatorCtx)) {
      const validated = validateTrace(result.trace);
      if (validated) metadata.trace = validated;
    }
    // If not allowed or invalid, trace is omitted
  }
  return {
    type: intent === "code" ? "code" : "text",
    content: result.content,
    metadata,
  };
}

async function mockChat(intent, content, messages) {
  // Simulate processing delay
  await new Promise((r) => setTimeout(r, 300 + Math.random() * 700));

  const hint = "[Requires a trained model. Run `python build.py --mode all --size tiny` first, then set MODEL_ENABLED=true.]";

  switch (intent) {
    case "image":
      return {
        type: "image",
        content: `I've generated an image based on your prompt: "${content}"\n\n${hint}`,
        metadata: { prompt: content, resolution: 256, model: "framerai-diffusion" },
      };

    case "video":
      return {
        type: "video",
        content: `I've started generating a video for: "${content}"\n\n${hint}`,
        metadata: { prompt: content, frames: 16, model: "framerai-video" },
      };

    case "audio":
      return {
        type: "audio",
        content: `I've generated audio for: "${content}"\n\n${hint}`,
        metadata: { prompt: content, model: "framerai-audio" },
      };

    case "code":
      return {
        type: "code",
        content: generateCodeResponse(content),
        metadata: { language: "python", model: "framerai-code" },
      };

    default:
      return {
        type: "text",
        content: generateTextResponse(content, messages),
        metadata: { model: "framerai-text" },
      };
  }
}

/**
 * Generate a text response (placeholder).
 */
function generateTextResponse(content, messages) {
  const lower = content.toLowerCase();

  if (lower.includes("hello") || lower.includes("hi") || lower.includes("hey")) {
    return "Hello! I'm FramerAI, a multimodal AI assistant. I can help you with:\n\n- **Text Generation** - Ask me anything\n- **Code Generation** - Write code in any language\n- **Image Generation** - Create images from descriptions\n- **Video Generation** - Generate short video clips\n- **Audio Generation** - Synthesize speech and audio\n\nHow can I help you today?";
  }

  if (lower.includes("what can you do") || lower.includes("capabilities") || lower.includes("help")) {
    return "I'm FramerAI, and here's what I can do:\n\n1. **Chat & Answer Questions** - General knowledge and conversation\n2. **Write Code** - Generate code in Python, JavaScript, and more\n3. **Generate Images** - Create images from text descriptions\n4. **Generate Videos** - Create short video clips from prompts\n5. **Generate Audio** - Synthesize speech and audio from text\n6. **Understand Images & Audio** - Analyze uploaded media\n\nJust describe what you need!";
  }

  if (lower.includes("who are you") || lower.includes("what are you")) {
    return "I'm **FramerAI**, an open-source multimodal AI model. I'm built with a transformer backbone for text and code, a diffusion model for images, temporal diffusion for video, and a mel-diffusion module for audio. I'm trained from scratch on local data - no external teacher models.";
  }

  return `I understand your message: "${content}"\n\nAs FramerAI, I can help with text, code, image, video, and audio generation. To unlock full capabilities, train the model:\n\n\`\`\`bash\npython build.py --mode all --size tiny\n\`\`\`\n\nThen set MODEL_ENABLED=true and restart the backend.`;
}

async function generateImage(prompt, numImages = 1, size = {}, requestId = null) {
  // The worker resolves the final dimensions: explicit width/height win, then an
  // aspect ratio at a size tier, then whatever the prompt itself asks for, then
  // the configured default. It reports back what it understood.
  const payload = { prompt, num_images: numImages };
  for (const key of ["width", "height", "aspect", "tier", "seed", "resolution"]) {
    if (size[key] !== undefined && size[key] !== null) payload[key] = size[key];
  }

  if (bridge.available()) {
    try {
      const result = await bridge.request("image", payload, requestId);
      return {
        id: randomUUID(),
        prompt,
        images: [{ id: randomUUID(), url: `${GENERATED_URL}/${result.file}`, placeholder: false }],
        metadata: {
          width: result.width,
          height: result.height,
          aspect: result.aspect,
          source: result.source,
          snapped: result.snapped,
          seed: result.seed,
          model: "framerai-diffusion",
        },
      };
    } catch (err) {
      logger.warn("image fallback", { error: err.message, requestId });
    }
  }
  return {
    id: randomUUID(),
    prompt,
    images: Array.from({ length: numImages }, () => ({
      id: randomUUID(),
      url: null,
      placeholder: true,
      message: "Train the model to generate actual images",
    })),
    metadata: { ...size, model: "framerai-diffusion" },
  };
}

async function generateVideo(prompt, numFrames = 16, requestId = null) {
  if (bridge.available()) {
    try {
      const result = await bridge.request("video", { prompt, num_frames: numFrames }, requestId);
      return {
        id: randomUUID(),
        prompt,
        video: { url: `${GENERATED_URL}/${result.file}`, frames: numFrames, placeholder: false },
        metadata: { frames: numFrames, model: "framerai-video" },
      };
    } catch (err) {
      logger.warn("video fallback", { error: err.message, requestId });
    }
  }
  return {
    id: randomUUID(),
    prompt,
    video: { url: null, frames: numFrames, placeholder: true, message: "Train the model to generate actual videos" },
    metadata: { frames: numFrames, model: "framerai-video" },
  };
}

async function generateAudio(prompt, settings = {}, requestId = null) {
  if (bridge.available()) {
    try {
      const result = await bridge.request("audio", { prompt, ...settings }, requestId);
      return {
        id: randomUUID(),
        prompt,
        audio: { url: `${GENERATED_URL}/${result.file}`, placeholder: false },
        metadata: { model: "framerai-audio" },
      };
    } catch (err) {
      logger.warn("audio fallback", { error: err.message, requestId });
    }
  }
  return {
    id: randomUUID(),
    prompt,
    audio: { url: null, placeholder: true, message: "Train the model to generate actual audio" },
    metadata: { model: "framerai-audio" },
  };
}

async function generateCode(prompt, language = "python", settings = {}, requestId = null) {
  if (bridge.available()) {
    try {
      const result = await bridge.request("code", { prompt, language, ...settings }, requestId);
      return { id: randomUUID(), prompt, code: result.content, language, metadata: { model: "framerai-code" } };
    } catch (err) {
      logger.warn("code fallback", { error: err.message, requestId });
    }
  }
  return {
    id: randomUUID(),
    prompt,
    code: generateCodeResponse(prompt),
    language,
    metadata: { model: "framerai-code" },
  };
}

async function transcribeAudio(audioPath, prompt = "Transcribe the audio:", requestId = null) {
  if (bridge.available()) {
    try {
      const result = await bridge.request("transcribe", { audio_path: audioPath, prompt }, requestId);
      return { text: result.content, metadata: { model: "framerai-audio" } };
    } catch (err) {
      logger.warn("transcribe fallback", { error: err.message, requestId });
    }
  }
  return {
    text: "[FramerAI Audio Analysis]\nThis is a placeholder transcription. Train the model and set MODEL_ENABLED=true for real transcription.",
    metadata: { model: "framerai-audio" },
  };
}

async function understandImage(imagePath, prompt = "Describe this image", requestId = null) {
  if (bridge.available()) {
    try {
      const result = await bridge.request("understand", { image_path: imagePath, prompt }, requestId);
      return { description: result.content };
    } catch (err) {
      logger.warn("understand fallback", { error: err.message, requestId });
    }
  }
  return {
    description: `[FramerAI Vision Analysis]\nPrompt: ${prompt}\n\nThis is a placeholder response. Train a FramerAI model and set MODEL_ENABLED=true for real vision analysis.`,
  };
}

module.exports = {
  processMessage,
  generateImage,
  generateVideo,
  generateAudio,
  generateCode,
  transcribeAudio,
  understandImage,
  validateTrace,
};
