/**
 * Model service - interfaces with the FramerAI Python model.
 *
 * In production, this would spawn a Python process or call a model server.
 * For development, it provides intelligent placeholder responses.
 */

const { v4: uuidv4 } = require("uuid");

/**
 * Detect the intent/type of a user message.
 */
function detectIntent(content) {
  const lower = content.toLowerCase();
  if (
    lower.includes("generate image") ||
    lower.includes("create image") ||
    lower.includes("draw") ||
    lower.includes("picture of")
  ) {
    return "image";
  }
  if (
    lower.includes("generate video") ||
    lower.includes("create video") ||
    lower.includes("animate") ||
    lower.includes("video of")
  ) {
    return "video";
  }
  if (
    lower.includes("write code") ||
    lower.includes("implement") ||
    lower.includes("function") ||
    lower.includes("```") ||
    lower.includes("code for") ||
    lower.includes("program")
  ) {
    return "code";
  }
  return "text";
}

/**
 * Generate a code response based on the prompt.
 */
function generateCodeResponse(prompt) {
  const lower = prompt.toLowerCase();

  if (lower.includes("fibonacci")) {
    return `\`\`\`python
def fibonacci(n):
    """Generate the nth Fibonacci number."""
    if n <= 0:
        return 0
    elif n == 1:
        return 1

    a, b = 0, 1
    for _ in range(2, n + 1):
        a, b = b, a + b
    return b


# Example usage
for i in range(10):
    print(f"F({i}) = {fibonacci(i)}")
\`\`\``;
  }

  if (lower.includes("sort") || lower.includes("sorting")) {
    return `\`\`\`python
def quicksort(arr):
    """Quicksort implementation."""
    if len(arr) <= 1:
        return arr

    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]

    return quicksort(left) + middle + quicksort(right)


# Example
data = [64, 34, 25, 12, 22, 11, 90]
print(f"Sorted: {quicksort(data)}")
\`\`\``;
  }

  if (lower.includes("api") || lower.includes("server") || lower.includes("express")) {
    return `\`\`\`javascript
const express = require('express');
const app = express();

app.use(express.json());

const items = [];

app.get('/api/items', (req, res) => {
  res.json(items);
});

app.post('/api/items', (req, res) => {
  const item = { id: Date.now(), ...req.body };
  items.push(item);
  res.status(201).json(item);
});

app.listen(3000, () => {
  console.log('Server running on port 3000');
});
\`\`\``;
  }

  return `\`\`\`python
# FramerAI Generated Code
# Prompt: ${prompt}

def solution():
    """Generated solution based on the prompt."""
    # Implementation would be generated by the trained model
    pass

if __name__ == "__main__":
    solution()
\`\`\``;
}

/**
 * Process a chat message and return a response.
 */
async function processMessage(messages, requestType = "text") {
  const lastMessage = messages[messages.length - 1];
  const content = lastMessage.content;
  const intent = requestType !== "text" ? requestType : detectIntent(content);

  // Simulate processing delay
  await new Promise((r) => setTimeout(r, 300 + Math.random() * 700));

  switch (intent) {
    case "image":
      return {
        type: "image",
        content: `I've generated an image based on your prompt: "${content}"\n\n[Image generation requires a trained model. Run \`python build.py --mode all --size tiny\` to train the model first.]`,
        metadata: {
          prompt: content,
          resolution: 256,
          model: "framerai-diffusion",
        },
      };

    case "video":
      return {
        type: "video",
        content: `I've started generating a video for: "${content}"\n\n[Video generation requires a trained model. Run \`python build.py --mode all --size tiny\` to train the model first.]`,
        metadata: {
          prompt: content,
          frames: 16,
          model: "framerai-video",
        },
      };

    case "code":
      return {
        type: "code",
        content: generateCodeResponse(content),
        metadata: {
          language: "python",
          model: "framerai-code",
        },
      };

    default:
      return {
        type: "text",
        content: generateTextResponse(content, messages),
        metadata: { model: "framerai-text" },
      };
  }
}

/**
 * Generate a text response.
 */
function generateTextResponse(content, messages) {
  const lower = content.toLowerCase();

  if (lower.includes("hello") || lower.includes("hi") || lower.includes("hey")) {
    return "Hello! I'm FramerAI, a multimodal AI assistant. I can help you with:\n\n- **Text Generation** - Ask me anything\n- **Code Generation** - Write code in any language\n- **Image Generation** - Create images from descriptions\n- **Video Generation** - Generate short video clips\n\nHow can I help you today?";
  }

  if (lower.includes("what can you do") || lower.includes("capabilities") || lower.includes("help")) {
    return "I'm FramerAI, and here's what I can do:\n\n1. **Chat & Answer Questions** - General knowledge and conversation\n2. **Write Code** - Generate code in Python, JavaScript, and more\n3. **Generate Images** - Create images from text descriptions\n4. **Generate Videos** - Create short video clips from prompts\n5. **Understand Images** - Analyze and describe uploaded images\n\nJust describe what you need!";
  }

  if (lower.includes("who are you") || lower.includes("what are you")) {
    return "I'm **FramerAI**, an open-source multimodal AI model. I'm built with a transformer backbone for text and code, a diffusion model for images, and a temporal diffusion model for video generation. I was created to be a versatile AI assistant that can understand and generate across multiple modalities.";
  }

  return `I understand your message: "${content}"\n\nAs FramerAI, I can help with text, code, images, and video generation. To unlock full capabilities, train the model using:\n\n\`\`\`bash\npython build.py --mode all --size tiny\n\`\`\`\n\nThen restart the backend to load the trained model.`;
}

async function generateImage(prompt, numImages = 1, resolution = 256) {
  return {
    id: uuidv4(),
    prompt,
    images: Array.from({ length: numImages }, (_, i) => ({
      id: uuidv4(),
      url: null,
      placeholder: true,
      message: "Train the model to generate actual images",
    })),
    metadata: { resolution, model: "framerai-diffusion" },
  };
}

async function generateVideo(prompt, numFrames = 16) {
  return {
    id: uuidv4(),
    prompt,
    video: {
      url: null,
      frames: numFrames,
      placeholder: true,
      message: "Train the model to generate actual videos",
    },
    metadata: { frames: numFrames, model: "framerai-video" },
  };
}

async function generateCode(prompt, language = "python") {
  return {
    id: uuidv4(),
    prompt,
    code: generateCodeResponse(prompt),
    language,
    metadata: { model: "framerai-code" },
  };
}

module.exports = { processMessage, generateImage, generateVideo, generateCode };
