/**
 * Model service.
 *
 * Routes each request to the FramerAI Python inference worker when a trained
 * checkpoint is available (see pythonBridge). When the model is disabled or the
 * worker is unavailable, it returns placeholder responses so the backend still
 * runs end to end without trained weights.
 */

const { randomUUID } = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");
const bridge = require("./pythonBridge");
const { logger } = require("./logger");
const config = require("../config");

const GENERATED_URL = "/uploads/generated";

/**
 * Detect the intent/type of a user message.
 */
function detectIntent(content) {
  const lower = content.toLowerCase();
  if (
    lower.includes("generate image") ||
    lower.includes("create image") ||
    lower.includes("draw") ||
    lower.includes("picture of")
  ) {
    return "image";
  }
  if (
    lower.includes("generate video") ||
    lower.includes("create video") ||
    lower.includes("animate") ||
    lower.includes("video of")
  ) {
    return "video";
  }
  if (
    lower.includes("generate audio") ||
    lower.includes("text to speech") ||
    lower.includes("speak") ||
    lower.includes("say ") ||
    lower.includes("voice") ||
    lower.includes("sound of")
  ) {
    return "audio";
  }
  if (
    lower.includes("write code") ||
    lower.includes("implement") ||
    lower.includes("function") ||
    lower.includes("```") ||
    lower.includes("code for") ||
    lower.includes("program")
  ) {
    return "code";
  }
  return "text";
}

/**
 * Generate a code response based on the prompt.
 */
function generateCodeResponse(prompt) {
  const lower = prompt.toLowerCase();

  if (lower.includes("fibonacci")) {
    return `\`\`\`python
def fibonacci(n):
    """Generate the nth Fibonacci number."""
    if n <= 0:
        return 0
    elif n == 1:
        return 1

    a, b = 0, 1
    for _ in range(2, n + 1):
        a, b = b, a + b
    return b


# Example usage
for i in range(10):
    print(f"F({i}) = {fibonacci(i)}")
\`\`\``;
  }

  if (lower.includes("sort") || lower.includes("sorting")) {
    return `\`\`\`python
def quicksort(arr):
    """Quicksort implementation."""
    if len(arr) <= 1:
        return arr

    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]

    return quicksort(left) + middle + quicksort(right)


# Example
data = [64, 34, 25, 12, 22, 11, 90]
print(f"Sorted: {quicksort(data)}")
\`\`\``;
  }

  if (lower.includes("api") || lower.includes("server") || lower.includes("express")) {
    return `\`\`\`javascript
const express = require('express');
const app = express();

app.use(express.json());

const items = [];

app.get('/api/items', (req, res) => {
  res.json(items);
});

app.post('/api/items', (req, res) => {
  const item = { id: Date.now(), ...req.body };
  items.push(item);
  res.status(201).json(item);
});

app.listen(3000, () => {
  console.log('Server running on port 3000');
});
\`\`\``;
  }

  return `\`\`\`python
# FramerAI Generated Code
# Prompt: ${prompt}

def solution():
    """Generated solution based on the prompt."""
    # Implementation would be generated by the trained model
    pass

if __name__ == "__main__":
    solution()
\`\`\``;
}

/**
 * Canonical cognition-trace schema.
 *
 * A trace is only forwarded when it is structurally valid AND the request
 * context permits it (privacy requirement: recalled memories may contain
 * earlier user content, so traces are gated behind INCLUDE_TRACE or an
 * operator-context header).
 *
 * Shape: {
 *   memories?:   Array<{ text: string, score: number }>,
 *   affect?:     Array<number>,               // affective vector
 *   affect_adj?: number,                       // sampling temperature adjustment
 *   sampling?:   Record<string, number>,       // top-k, top-p, etc.
 *   tools?:      Array<{ name, input, output }>,
 * }
 */
function validateTrace(trace) {
  if (!trace || typeof trace !== "object" || Array.isArray(trace)) return null;

  const cleaned = {};
  let hasContent = false;

  if (Array.isArray(trace.memories) && trace.memories.length > 0) {
    cleaned.memories = trace.memories.map((m) => ({
      text: String(m?.text ?? ""),
      score: Number(m?.score) || 0,
    }));
    hasContent = true;
  }

  if (Array.isArray(trace.affect) && trace.affect.length > 0) {
    cleaned.affect = trace.affect.map((v) => Number(v) || 0);
    hasContent = true;
  }

  if (trace.affect_adj != null && !isNaN(Number(trace.affect_adj))) {
    cleaned.affect_adj = Number(trace.affect_adj);
    hasContent = true;
  }

  if (trace.sampling && typeof trace.sampling === "object" && !Array.isArray(trace.sampling)) {
    const samplingEntries = Object.entries(trace.sampling).map(([k, v]) => [k, Number(v) || 0]);
    if (samplingEntries.length > 0) {
      cleaned.sampling = Object.fromEntries(samplingEntries);
      hasContent = true;
    }
  }

  if (Array.isArray(trace.tools) && trace.tools.length > 0) {
    cleaned.tools = trace.tools;
    hasContent = true;
  }

  // Return null if trace is empty (no meaningful content)
  return hasContent ? cleaned : null;
}

/**
 * Returns true when the caller context allows cognition traces to be forwarded.
 * Traces contain recalled memories which may include earlier user content, so
 * they are only sent when explicitly opted in.
 *
 * `INCLUDE_TRACE` is a server-side switch and is always honoured. The operator
 * flag comes from a request header, which a client can set for itself, so it is
 * only honoured when a proxy is trusted to set it — the same rule the WebSocket
 * rate limiter applies to `x-forwarded-for`. Without that guard anyone could
 * ask for the trace by name and read back the recalled memories.
 *
 * @param {object|null} operatorContext - headers or flags from the caller
 */
function traceAllowed(operatorContext) {
  if (process.env.INCLUDE_TRACE === "true") return true;
  if (config.trustProxy && operatorContext?.operator === true) return true;
  return false;
}

/**
 * Normalizes options and requestId parameter combinations into a uniform object structure.
 * Supports both options object ({ onApprovalRequest, requestId, operatorCtx }) and
 * legacy positional arguments (requestId, operatorCtx).
 */
function normalizeModelOptions(requestIdOrOptions, operatorCtxParam) {
  let requestId = null;
  let operatorCtx = null;
  let onApprovalRequest = null;
  let optionsObj = {};

  if (typeof requestIdOrOptions === "string") {
    requestId = requestIdOrOptions;
    operatorCtx = operatorCtxParam || null;
    optionsObj = { requestId, operatorCtx };
  } else if (requestIdOrOptions && typeof requestIdOrOptions === "object") {
    optionsObj = requestIdOrOptions;
    requestId = requestIdOrOptions.requestId || (typeof operatorCtxParam === "string" ? operatorCtxParam : null);
    operatorCtx = requestIdOrOptions.operatorCtx || (typeof operatorCtxParam === "object" ? operatorCtxParam : null);
    onApprovalRequest = requestIdOrOptions.onApprovalRequest || null;
  } else {
    operatorCtx = operatorCtxParam || null;
    optionsObj = { operatorCtx };
  }

  return {
    requestId,
    operatorCtx,
    onApprovalRequest,
    options: optionsObj,
  };
}

const UPLOADS_ROOT = path.join(__dirname, "..", "..", "uploads");
const UPLOAD_PREFIX = "/uploads/";
// Which encoder an attachment reaches, keyed by the directory it was stored in.
const ATTACHMENT_KINDS = {
  images: "image",
  audio: "audio",
  documents: "document",
  generated: "image",
};

/**
 * Turn client-supplied attachment references into paths the worker may open.
 *
 * Only files this server stored are addressable. Each reference is resolved and
 * then checked to still sit under the uploads root, so a "../" in a supplied
 * name cannot walk out into the rest of the filesystem. Anything that fails a
 * check is dropped with a log line rather than passed on, because a bad
 * reference should cost the caller its attachment, not the whole request.
 */
function resolveAttachments(attachments, requestId = null) {
  if (!Array.isArray(attachments) || attachments.length === 0) return [];

  const resolved = [];
  for (const entry of attachments) {
    const raw = typeof entry === "string" ? entry : entry && entry.path;
    if (typeof raw !== "string" || !raw.startsWith(UPLOAD_PREFIX)) {
      logger.warn("attachment ignored", { reason: "not an uploads path", requestId });
      continue;
    }

    const full = path.resolve(UPLOADS_ROOT, raw.slice(UPLOAD_PREFIX.length));
    if (!full.startsWith(UPLOADS_ROOT + path.sep)) {
      logger.warn("attachment ignored", { reason: "outside the uploads root", requestId });
      continue;
    }

    const bucket = path.relative(UPLOADS_ROOT, full).split(path.sep)[0];
    const kind = ATTACHMENT_KINDS[bucket];
    if (!kind) {
      logger.warn("attachment ignored", { reason: `unknown bucket '${bucket}'`, requestId });
      continue;
    }
    if (!fs.existsSync(full)) {
      logger.warn("attachment ignored", { reason: "no such file", requestId });
      continue;
    }
    resolved.push({ path: full, kind });
  }
  return resolved;
}

async function processMessage(messages, requestType = "text", settings = {}, requestIdOrOptions = null, operatorCtxParam = null) {
  const opts = normalizeModelOptions(requestIdOrOptions, operatorCtxParam);
  const lastMessage = messages[messages.length - 1];
  const content = lastMessage.content;
  const intent = requestType !== "text" ? requestType : detectIntent(content);
  // Attachments were validated and stored and then never read, so nothing a
  // user attached had ever reached the model.
  const attachments = resolveAttachments(lastMessage.attachments, opts.requestId);
  // History reached the model as a single string, so every turn arrived with no
  // prior context however large the window was. The worker has accepted a
  // messages array all along; this is the first caller to send one.
  const history = conversationHistory(messages);

  if (bridge.available()) {
    try {
      return await modelChat(intent, content, settings, opts.options, null, attachments, history);
    } catch (err) {
      logger.warn("falling back to placeholder", { error: err.message, requestId: opts.requestId });
    }
  }

  return mockChat(intent, content, messages);
}

/**
 * The turns worth sending, as the worker's chat template expects them.
 *
 * Returns null for a single-turn exchange, so a one-message conversation is
 * sent exactly as it was before rather than as a one-element array.
 */
function conversationHistory(messages) {
  if (!Array.isArray(messages) || messages.length < 2) return null;
  return messages
    .filter((m) => m && typeof m.content === "string" && m.content && m.role)
    .map((m) => ({ role: m.role, content: m.content }));
}

async function modelChat(intent, content, settings = {}, requestIdOrOptions = null, operatorCtxParam = null, attachments = [], history = null) {
  const opts = normalizeModelOptions(requestIdOrOptions, operatorCtxParam);

  if (intent === "image" || intent === "video" || intent === "audio") {
    const result = await bridge.request(intent, { prompt: content, ...settings }, opts.options);
    return {
      type: intent,
      content: `Here is the ${intent} generated for: "${content}"`,
      metadata: { prompt: content, url: `${GENERATED_URL}/${result.file}`, model: `framerai-${intent}` },
    };
  }

  const op = intent === "code" ? "code" : "chat";
  // The worker takes a prompt or a messages array, not both: it builds the
  // prompt from the messages when one is given, so sending both would let the
  // single turn win and drop the history again.
  const params = history && history.length > 1
    ? { messages: history, ...settings }
    : { prompt: content, ...settings };
  if (attachments.length) params.attachments = attachments;
  const result = await bridge.request(op, params, opts.options);
  const metadata = { model: `framerai-${intent === "code" ? "code" : "text"}` };
  // Report what actually reached the model, so a dropped attachment is visible
  // rather than looking like the model ignored it.
  if (attachments.length) metadata.attachments = attachments.map((a) => a.kind);
  // Tool steps travel with the reply so the UI can show what was searched and
  // read instead of presenting a sourced answer as if it came from the weights.
  if (result.tools) metadata.tools = result.tools;
  // Cognition trace — only forwarded when the operator context permits it
  // (privacy: recalled memories may contain earlier user content).
  // Strip it from the result if not allowed, even if Python sent it.
  if (result.trace) {
    if (traceAllowed(opts.operatorCtx)) {
      const validated = validateTrace(result.trace);
      if (validated) metadata.trace = validated;
    }
    // If not allowed or invalid, trace is omitted
  }
  return {
    type: intent === "code" ? "code" : "text",
    content: result.content,
    metadata,
  };
}

async function mockChat(intent, content, messages) {
  // Simulate processing delay
  await new Promise((r) => setTimeout(r, 300 + Math.random() * 700));

  const hint = "[Requires a trained model. Run `python build.py --mode all --size tiny` first, then set MODEL_ENABLED=true.]";

  switch (intent) {
    case "image":
      return {
        type: "image",
        content: `I've generated an image based on your prompt: "${content}"\n\n${hint}`,
        metadata: { prompt: content, resolution: 256, model: "framerai-diffusion" },
      };

    case "video":
      return {
        type: "video",
        content: `I've started generating a video for: "${content}"\n\n${hint}`,
        metadata: { prompt: content, frames: 16, model: "framerai-video" },
      };

    case "audio":
      return {
        type: "audio",
        content: `I've generated audio for: "${content}"\n\n${hint}`,
        metadata: { prompt: content, model: "framerai-audio" },
      };

    case "code":
      return {
        type: "code",
        content: generateCodeResponse(content),
        metadata: { language: "python", model: "framerai-code" },
      };

    default:
      return {
        type: "text",
        content: generateTextResponse(content, messages),
        metadata: { model: "framerai-text" },
      };
  }
}

/**
 * Generate a text response (placeholder).
 */
function generateTextResponse(content, messages) {
  const lower = content.toLowerCase();

  if (lower.includes("hello") || lower.includes("hi") || lower.includes("hey")) {
    return "Hello! I'm FramerAI, a multimodal AI assistant. I can help you with:\n\n- **Text Generation** - Ask me anything\n- **Code Generation** - Write code in any language\n- **Image Generation** - Create images from descriptions\n- **Video Generation** - Generate short video clips\n- **Audio Generation** - Synthesize speech and audio\n\nHow can I help you today?";
  }

  if (lower.includes("what can you do") || lower.includes("capabilities") || lower.includes("help")) {
    return "I'm FramerAI, and here's what I can do:\n\n1. **Chat & Answer Questions** - General knowledge and conversation\n2. **Write Code** - Generate code in Python, JavaScript, and more\n3. **Generate Images** - Create images from text descriptions\n4. **Generate Videos** - Create short video clips from prompts\n5. **Generate Audio** - Synthesize speech and audio from text\n6. **Understand Images & Audio** - Analyze uploaded media\n\nJust describe what you need!";
  }

  if (lower.includes("who are you") || lower.includes("what are you")) {
    return "I'm **FramerAI**, an open-source multimodal AI model. I'm built with a transformer backbone for text and code, a diffusion model for images, temporal diffusion for video, and a mel-diffusion module for audio. I'm trained from scratch on local data - no external teacher models.";
  }

  return `I understand your message: "${content}"\n\nAs FramerAI, I can help with text, code, image, video, and audio generation. To unlock full capabilities, train the model:\n\n\`\`\`bash\npython build.py --mode all --size tiny\n\`\`\`\n\nThen set MODEL_ENABLED=true and restart the backend.`;
}

async function generateImage(prompt, numImages = 1, size = {}, requestIdOrOptions = null) {
  const opts = normalizeModelOptions(requestIdOrOptions);
  // The worker resolves the final dimensions: explicit width/height win, then an
  // aspect ratio at a size tier, then whatever the prompt itself asks for, then
  // the configured default. It reports back what it understood.
  const payload = { prompt, num_images: numImages };
  for (const key of ["width", "height", "aspect", "tier", "seed", "resolution"]) {
    if (size[key] !== undefined && size[key] !== null) payload[key] = size[key];
  }

  if (bridge.available()) {
    try {
      const result = await bridge.request("image", payload, opts.options);
      return {
        id: randomUUID(),
        prompt,
        images: [{ id: randomUUID(), url: `${GENERATED_URL}/${result.file}`, placeholder: false }],
        metadata: {
          width: result.width,
          height: result.height,
          aspect: result.aspect,
          source: result.source,
          snapped: result.snapped,
          seed: result.seed,
          model: "framerai-diffusion",
        },
      };
    } catch (err) {
      logger.warn("image fallback", { error: err.message, requestId: opts.requestId });
    }
  }
  return {
    id: randomUUID(),
    prompt,
    images: Array.from({ length: numImages }, () => ({
      id: randomUUID(),
      url: null,
      placeholder: true,
      message: "Train the model to generate actual images",
    })),
    metadata: { ...size, model: "framerai-diffusion" },
  };
}

async function generateVideo(prompt, numFrames = 16, size = {}, requestIdOrOptions = null) {
  // Older callers passed the request id where the size now sits.
  if (typeof size === "string" || (size && size.requestId && requestIdOrOptions === null)) {
    requestIdOrOptions = size;
    size = {};
  }
  const opts = normalizeModelOptions(requestIdOrOptions);

  if (bridge.available()) {
    try {
      const params = { prompt, num_frames: numFrames };
      for (const key of ["width", "height", "aspect", "tier", "fps", "seed"]) {
        if (size[key] !== undefined && size[key] !== null) params[key] = size[key];
      }
      const result = await bridge.request("video", params, opts.options);
      // The frame count came back as the number requested rather than the
      // number produced, so a clip the decoder trimmed reported a length it
      // did not have.
      const frames = Number.isFinite(result.frames) ? result.frames : numFrames;
      const fps = result.fps || size.fps || 24;
      return {
        id: randomUUID(),
        prompt,
        video: { url: `${GENERATED_URL}/${result.file}`, frames, fps, placeholder: false },
        metadata: { frames, fps, width: result.width, height: result.height, model: "framerai-video" },
      };
    } catch (err) {
      logger.warn("video fallback", { error: err.message, requestId: opts.requestId });
    }
  }
  const fps = size.fps || 24;
  return {
    id: randomUUID(),
    prompt,
    video: { url: null, frames: numFrames, fps, placeholder: true, message: "Train the model to generate actual videos" },
    metadata: { frames: numFrames, fps, model: "framerai-video" },
  };
}

async function generateAudio(prompt, settings = {}, requestIdOrOptions = null) {
  const opts = normalizeModelOptions(requestIdOrOptions);
  if (bridge.available()) {
    try {
      const result = await bridge.request("audio", { prompt, ...settings }, opts.options);
      return {
        id: randomUUID(),
        prompt,
        audio: { url: `${GENERATED_URL}/${result.file}`, placeholder: false },
        metadata: { model: "framerai-audio" },
      };
    } catch (err) {
      logger.warn("audio fallback", { error: err.message, requestId: opts.requestId });
    }
  }
  return {
    id: randomUUID(),
    prompt,
    audio: { url: null, placeholder: true, message: "Train the model to generate actual audio" },
    metadata: { model: "framerai-audio" },
  };
}

async function generateCode(prompt, language = "python", settings = {}, requestIdOrOptions = null) {
  const opts = normalizeModelOptions(requestIdOrOptions);
  if (bridge.available()) {
    try {
      const result = await bridge.request("code", { prompt, language, ...settings }, opts.options);
      return { id: randomUUID(), prompt, code: result.content, language, metadata: { model: "framerai-code" } };
    } catch (err) {
      logger.warn("code fallback", { error: err.message, requestId: opts.requestId });
    }
  }
  return {
    id: randomUUID(),
    prompt,
    code: generateCodeResponse(prompt),
    language,
    metadata: { model: "framerai-code" },
  };
}

async function transcribeAudio(audioPath, prompt = "Transcribe the audio:", requestIdOrOptions = null) {
  const opts = normalizeModelOptions(requestIdOrOptions);
  if (bridge.available()) {
    try {
      const result = await bridge.request("transcribe", { audio_path: audioPath, prompt }, opts.options);
      return { text: result.content, metadata: { model: "framerai-audio" } };
    } catch (err) {
      logger.warn("transcribe fallback", { error: err.message, requestId: opts.requestId });
    }
  }
  return {
    text: "[FramerAI Audio Analysis]\nThis is a placeholder transcription. Train the model and set MODEL_ENABLED=true for real transcription.",
    metadata: { model: "framerai-audio" },
  };
}

async function understandImage(imagePath, prompt = "Describe this image", requestIdOrOptions = null) {
  const opts = normalizeModelOptions(requestIdOrOptions);
  if (bridge.available()) {
    try {
      const result = await bridge.request("understand", { image_path: imagePath, prompt }, opts.options);
      return { description: result.content };
    } catch (err) {
      logger.warn("understand fallback", { error: err.message, requestId: opts.requestId });
    }
  }
  return {
    description: `[FramerAI Vision Analysis]\nPrompt: ${prompt}\n\nThis is a placeholder response. Train a FramerAI model and set MODEL_ENABLED=true for real vision analysis.`,
  };
}

async function readDocument(documentPath, prompt = "", requestIdOrOptions = null) {
  const opts = normalizeModelOptions(requestIdOrOptions);
  const maxPages = requestIdOrOptions && requestIdOrOptions.maxPages;

  if (bridge.available()) {
    try {
      const params = { document_path: documentPath, prompt };
      if (maxPages) params.max_pages = maxPages;
      const result = await bridge.request("document", params, opts.options);

      // An absent optional reader is a deployment fact the caller can act on,
      // so it is passed up as an error rather than dressed as placeholder text.
      // The route turns it into a response; the service stays free of HTTP.
      if (result.error) {
        return { error: result.error, code: result.code || "DOCUMENT_UNREADABLE" };
      }
      return {
        text: result.text,
        pages: result.pages,
        title: result.title || "",
        scannedPages: result.scanned_pages || [],
        content: result.content,
        metadata: { model: "framerai-document" },
      };
    } catch (err) {
      logger.warn("document fallback", { error: err.message, requestId: opts.requestId });
    }
  }
  return {
    text: "",
    pages: 0,
    title: "",
    scannedPages: [],
    content:
      "[FramerAI Document Analysis]\nThis is a placeholder response. Train the model and set MODEL_ENABLED=true to read documents.",
    metadata: { model: "framerai-document" },
  };
}

module.exports = {
  processMessage,
  generateImage,
  generateVideo,
  generateAudio,
  generateCode,
  transcribeAudio,
  understandImage,
  readDocument,
  resolveAttachments,
  conversationHistory,
  validateTrace,
  traceAllowed,
};
