/**
 * WebSocket service for real-time streaming responses.
 */

const { randomUUID } = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");
const model = require("./model");
const { generationCounter } = require("../middleware/limiters");
const config = require("../config");
const { createLogger } = require("./logger");

const { validator } = require("../middleware/validate");
const { readSettings } = require("../generationSettings");

const MESSAGE_TYPES = ["text", "code", "image", "video", "audio"];
const MAX_MESSAGE_LENGTH = 8000;

// Audio chunk size: 0.5 seconds of 16-bit mono PCM
// This provides smooth incremental playback without excessive message overhead
const AUDIO_CHUNK_DURATION_SEC = 0.5;

/**
 * Validate an incoming chat frame the same way the REST route does, so a bad
 * frame gets a clear error instead of failing somewhere in the model service.
 */
function parseChatFrame(message) {
  const content = typeof message.content === "string" ? message.content.trim() : "";
  if (!content) throw new Error("content is required");
  if (content.length > MAX_MESSAGE_LENGTH) {
    throw new Error(`content must be at most ${MAX_MESSAGE_LENGTH} characters`);
  }

  const messageType = message.messageType || "text";
  if (!MESSAGE_TYPES.includes(messageType)) {
    throw new Error(`messageType must be one of: ${MESSAGE_TYPES.join(", ")}`);
  }

  // Same bounds as the REST routes. Out-of-range values are reported rather
  // than quietly clamped, so a client cannot think a setting took effect.
  const v = validator(message);
  const settings = readSettings(v);
  if (v.errors.length) {
    const [first] = v.errors;
    throw new Error(`${first.field} ${first.message}`);
  }

  const attachments = Array.isArray(message.attachments) ? message.attachments.slice(0, 10) : [];

  return { content, messageType, settings, attachments, conversationId: message.conversationId };
}

/**
 * Parse a WAV file and extract PCM audio data with metadata.
 * Assumes mono 16-bit PCM format (the format generated by model/serve.py).
 */
function parseWavFile(filePath) {
  const buffer = fs.readFileSync(filePath);

  // Minimal WAV header parsing - we know the format from serve.py
  // RIFF header (12 bytes) + fmt chunk (24 bytes) + data chunk header (8 bytes) = 44 bytes
  if (buffer.length < 44) {
    throw new Error("WAV file too small");
  }

  // Verify RIFF header
  if (buffer.toString("ascii", 0, 4) !== "RIFF") {
    throw new Error("Not a valid WAV file");
  }

  // Read format details
  const channels = buffer.readUInt16LE(22);
  const sampleRate = buffer.readUInt32LE(24);
  const bitsPerSample = buffer.readUInt16LE(34);

  // Find data chunk (skip to byte 36, read "data" marker and size)
  const dataMarker = buffer.toString("ascii", 36, 40);
  if (dataMarker !== "data") {
    throw new Error("WAV data chunk not found");
  }

  const dataSize = buffer.readUInt32LE(40);
  const pcmData = buffer.subarray(44, 44 + dataSize);

  return {
    channels,
    sampleRate,
    bitsPerSample,
    pcmData,
    durationSec: pcmData.length / (sampleRate * channels * (bitsPerSample / 8)),
  };
}

/**
 * Safely send a JSON payload over WebSocket only if the connection is OPEN.
 */
function safeSend(ws, payload) {
  if (ws && ws.readyState === 1 /* OPEN */) {
    try {
      ws.send(JSON.stringify(payload));
      return true;
    } catch (_) {
      return false;
    }
  }
  return false;
}

/**
 * Stream audio in chunks over WebSocket.
 * Reads the generated WAV file, extracts PCM data, and sends it in time-based chunks.
 */
async function streamAudio(ws, response, conversationId, wsLog) {
  const audioUrl = response.metadata?.url;
  if (!audioUrl) {
    // No audio file available, send non-streaming response
    safeSend(ws, {
      type: "stream",
      conversationId,
      content: response.content,
      done: true,
      responseType: "audio",
      metadata: response.metadata,
    });
    return;
  }

  try {
    // Resolve file path from URL
    const filePath = path.join(__dirname, "..", "..", audioUrl.replace(/^\//, ""));

    if (!fs.existsSync(filePath)) {
      throw new Error("Generated audio file not found");
    }

    const { channels, sampleRate, bitsPerSample, pcmData, durationSec } = parseWavFile(filePath);

    // Calculate chunk size in bytes
    const bytesPerSample = bitsPerSample / 8;
    const samplesPerChunk = Math.floor(sampleRate * AUDIO_CHUNK_DURATION_SEC);
    const bytesPerChunk = samplesPerChunk * channels * bytesPerSample;

    const totalChunks = Math.ceil(pcmData.length / bytesPerChunk);

    // Send audio chunks
    for (let i = 0; i < totalChunks; i++) {
      if (ws.readyState !== 1 /* OPEN */) break;

      const start = i * bytesPerChunk;
      const end = Math.min(start + bytesPerChunk, pcmData.length);
      const chunk = pcmData.subarray(start, end);
      const isLast = i === totalChunks - 1;

      const message = {
        type: "stream",
        conversationId,
        content: i === 0 ? response.content : "",
        done: isLast,
        responseType: "audio",
        metadata: {
          chunk: i,
          totalChunks,
          chunkData: chunk.toString("base64"),
          sampleRate,
          channels,
          bitsPerSample,
          ...(isLast ? {
            url: audioUrl,
            model: response.metadata.model,
            durationSec,
          } : {}),
        },
      };

      const sent = safeSend(ws, message);

      // Small delay between chunks to simulate streaming and avoid overwhelming the client
      if (!sent || isLast) break;
      await new Promise(r => setTimeout(r, 50));
    }
  } catch (err) {
    wsLog.error("audio streaming failed", { error: err.message });
    // Fallback: send non-streaming response with URL
    safeSend(ws, {
      type: "stream",
      conversationId,
      content: response.content,
      done: true,
      responseType: "audio",
      metadata: response.metadata,
    });
  }
}

function setupWebSocket(wss) {
  wss.on("connection", (ws, req) => {
    const clientId = randomUUID();
    const wsLog = createLogger({ connectionId: clientId });
    // Rate limit key. There is no Express request here, so read the socket
    // directly. The forwarded header is only honoured when a proxy is trusted,
    // otherwise a client could set it and get a fresh bucket per frame.
    const forwarded = config.trustProxy
      ? (req?.headers["x-forwarded-for"] || "").split(",")[0].trim()
      : "";
    const clientKey = forwarded || req?.socket?.remoteAddress || clientId;
    wsLog.info("WebSocket client connected");

    // Track approval state per session
    let denyEverything = false;
    const pendingApprovals = new Map();

    const cleanupApprovals = () => {
      for (const respond of pendingApprovals.values()) {
        try {
          respond(false);
        } catch {
          // ignore
        }
      }
      pendingApprovals.clear();
    };

    ws.on("message", async (data) => {
      try {
        const message = JSON.parse(data);

        if (message.type === "approval_response") {
          if (message.denyEverything) {
            denyEverything = true;
          }
          if (message.approvalId && pendingApprovals.has(message.approvalId)) {
            const respond = pendingApprovals.get(message.approvalId);
            pendingApprovals.delete(message.approvalId);
            respond(Boolean(message.approved));
          }
          return;
        }

        if (message.type === "chat") {
          const { content, conversationId, messageType, settings, attachments } = parseChatFrame(message);

          // Shares buckets with the REST generation routes, so the limit
          // cannot be sidestepped by switching transport.
          if (generationCounter.enabled) {
            const { allowed, retryAfter } = generationCounter.hit(clientKey);
            if (!allowed) {
              safeSend(ws, {
                type: "error",
                conversationId,
                code: "RATE_LIMITED",
                message: `Too many generation requests. Try again in ${retryAfter}s.`,
              });
              return;
            }
          }

          // Send acknowledgment
          safeSend(ws, {
            type: "ack",
            messageId: randomUUID(),
            conversationId,
          });

          // Send typing indicator
          safeSend(ws, { type: "typing", conversationId });

          // Process and stream response
          const messages = [{ role: "user", content, attachments }];
          const operatorCtx = { operator: req?.headers?.["x-operator"] === "true" };
          const onApprovalRequest = ({ approvalId, command, argv, root, respond }) => {
            if (denyEverything) {
              respond(false);
              return;
            }
            pendingApprovals.set(approvalId, respond);
            const sent = safeSend(ws, {
              type: "approval_request",
              approvalId,
              conversationId,
              command,
              argv,
              root,
            });
            if (!sent) {
              pendingApprovals.delete(approvalId);
              respond(false);
            }
          };

          const response = await model.processMessage(
            messages,
            messageType,
            settings,
            { onApprovalRequest, operatorCtx },
            operatorCtx
          );

          // Privacy: validate and strip trace from response if not allowed (defense in depth)
          if (response.metadata?.trace) {
            const validated = model.traceAllowed(operatorCtx) ? model.validateTrace(response.metadata.trace) : null;
            if (validated) {
              response.metadata.trace = validated;
            } else {
              delete response.metadata.trace;
            }
          }

          // Special handling for audio: stream PCM chunks
          if (response.type === "audio") {
            await streamAudio(ws, response, conversationId, wsLog);
            return;
          }

          // Normal text/code streaming by word-splitting
          const words = response.content.split(" ");
          let accumulated = "";

          for (let i = 0; i < words.length; i++) {
            if (ws.readyState !== 1 /* OPEN */) break;

            accumulated += (i > 0 ? " " : "") + words[i];
            const isDone = i === words.length - 1;
            const sent = safeSend(ws, {
              type: "stream",
              conversationId,
              content: accumulated,
              done: isDone,
              responseType: response.type,
              metadata: isDone ? response.metadata : undefined,
            });

            if (!sent || isDone) break;

            // Simulate token generation delay
            await new Promise((r) => setTimeout(r, 20 + Math.random() * 30));
          }
        }

        if (message.type === "ping") {
          safeSend(ws, { type: "pong" });
        }
      } catch (err) {
        safeSend(ws, { type: "error", message: err.message });
      }
    });

    ws.on("close", () => {
      wsLog.info("WebSocket client disconnected");
      cleanupApprovals();
    });

    ws.on("error", () => {
      cleanupApprovals();
    });
  });
}

module.exports = { setupWebSocket };
