/**
 * WebSocket service for real-time streaming responses.
 */

const { randomUUID } = require("node:crypto");
const fsp = require("node:fs/promises");
const path = require("node:path");
const model = require("./model");
const { generationCounter } = require("../middleware/limiters");
const { resolveClientIp } = require("../middleware/rateLimit");
const config = require("../config");
const { createLogger } = require("./logger");

const { validator } = require("../middleware/validate");
const { readSettings } = require("../generationSettings");
const modelLimits = require("../modelLimits");
const conversations = require("../conversationStore");

const MESSAGE_TYPES = ["text", "code", "image", "video", "audio"];

// Audio chunk size: 0.5 seconds of 16-bit mono PCM
// This provides smooth incremental playback without excessive message overhead
const AUDIO_CHUNK_DURATION_SEC = 0.5;

// Upper bound on the frames the simulated-streaming fallback emits. Each frame
// repeats the whole prefix, so bytes on the wire grow with frames × length;
// with one frame per word a reply built from a max-length prompt sent ~16 MB
// over ~3 minutes. 64 frames at the delay below is already more than a second
// of animation, which is as much as the effect is worth (Issue #364).
const MAX_SIMULATED_FRAMES = 64;

/**
 * Validate an incoming chat frame the same way the REST route does, so a bad
 * frame gets a clear error instead of failing somewhere in the model service.
 */
function parseChatFrame(message) {
  const content = typeof message.content === "string" ? message.content.trim() : "";
  if (!content) throw new Error("content is required");
  const maxContent = modelLimits.messageChars();
  if (content.length > maxContent) {
    throw new Error(`content must be at most ${maxContent} characters`);
  }

  const messageType = message.messageType || "text";
  if (!MESSAGE_TYPES.includes(messageType)) {
    throw new Error(`messageType must be one of: ${MESSAGE_TYPES.join(", ")}`);
  }

  // Same bounds as the REST routes. Out-of-range values are reported rather
  // than quietly clamped, so a client cannot think a setting took effect.
  const v = validator(message);

  // The id is handed straight to conversationStore and decides which stored
  // history this turn joins, so it gets the same shape check the REST route
  // makes with v.uuid("id") rather than a second, looser rule. Omitting it is
  // still a single-turn chat — long-standing behaviour — but an id that is sent
  // at all has to be well formed, the empty string included (Issue #352).
  if (message.conversationId !== undefined && message.conversationId !== null) {
    v.uuid("conversationId");
  }

  const settings = readSettings(v);
  if (v.errors.length) {
    const [first] = v.errors;
    throw new Error(`${first.field} ${first.message}`);
  }

  const attachments = Array.isArray(message.attachments) ? message.attachments.slice(0, 10) : [];

  return { content, messageType, settings, attachments, conversationId: message.conversationId };
}

/**
 * Parse a WAV file and extract PCM audio data with metadata.
 * Assumes mono 16-bit PCM format (the format generated by model/serve.py).
 *
 * Iterates RIFF sub-chunks to locate fmt  and data, so files that carry extra
 * metadata chunks (JUNK, LIST, …) between fmt  and data are handled correctly.
 *
 * The read is asynchronous: a synchronous read stalls the single event loop for
 * its whole duration, so one large or slow WAV delayed every other request the
 * process was serving (Issue #347). Parsing stays synchronous once the bytes
 * are in memory — it is pure buffer arithmetic and never touches the disk.
 */
async function parseWavFile(filePath) {
  const buffer = await fsp.readFile(filePath);

  // Minimum: RIFF/WAVE header (12 bytes) + at least one chunk header (8 bytes)
  if (buffer.length < 20) {
    throw new Error("WAV file too small");
  }
  if (buffer.toString("ascii", 0, 4) !== "RIFF") {
    throw new Error("Not a valid WAV file: missing RIFF signature");
  }
  if (buffer.toString("ascii", 8, 12) !== "WAVE") {
    throw new Error("Not a valid WAV file: missing WAVE signature");
  }

  let channels = null;
  let sampleRate = null;
  let bitsPerSample = null;
  let pcmData = null;

  // Walk RIFF sub-chunks starting after the WAVE fourCC (offset 12).
  // Each chunk: 4-byte ID + 4-byte LE size + <size> bytes of payload.
  // Per the RIFF spec, odd-sized chunks are followed by a padding byte.
  let offset = 12;
  while (offset + 8 <= buffer.length) {
    const chunkId = buffer.toString("ascii", offset, offset + 4);
    const chunkSize = buffer.readUInt32LE(offset + 4);

    if (offset + 8 + chunkSize > buffer.length) {
      throw new Error(`WAV chunk "${chunkId}" at offset ${offset} exceeds file size`);
    }

    if (chunkId === "fmt ") {
      if (chunkSize < 16) {
        throw new Error("WAV fmt chunk too small");
      }
      // fmt  fields are relative to the chunk data start (offset + 8).
      channels = buffer.readUInt16LE(offset + 10);     // audioFormat(2) + channels(2)
      sampleRate = buffer.readUInt32LE(offset + 12);   // + sampleRate(4)
      bitsPerSample = buffer.readUInt16LE(offset + 22); // + byteRate(4) + blockAlign(2) + bitsPerSample(2)
      // None of these may be zero: durationSec below divides by their product,
      // and a consumer sizes its chunks from them, so a zero yields a
      // non-finite duration and chunk count rather than a playable stream
      // (Issue #362).
      if (channels <= 0 || sampleRate <= 0 || bitsPerSample <= 0) {
        throw new Error(
          "WAV fmt chunk declares unusable values: " +
            `channels=${channels}, sampleRate=${sampleRate}, bitsPerSample=${bitsPerSample}`
        );
      }
    } else if (chunkId === "data") {
      if (channels === null) {
        throw new Error("WAV data chunk found before fmt chunk");
      }
      pcmData = buffer.subarray(offset + 8, offset + 8 + chunkSize);
      break;
    }

    offset += 8 + chunkSize + (chunkSize % 2); // advance past this chunk (even boundary)
  }

  if (pcmData === null) {
    throw new Error("WAV data chunk not found");
  }

  return {
    channels,
    sampleRate,
    bitsPerSample,
    pcmData,
    durationSec: pcmData.length / (sampleRate * channels * (bitsPerSample / 8)),
  };
}

/**
 * Safely send a JSON payload over WebSocket only if the connection is OPEN.
 */
function safeSend(ws, payload) {
  if (ws && ws.readyState === 1 /* OPEN */) {
    try {
      ws.send(JSON.stringify(payload));
      return true;
    } catch (_) {
      return false;
    }
  }
  return false;
}

/**
 * Stream audio in chunks over WebSocket.
 * Reads the generated WAV file, extracts PCM data, and sends it in time-based chunks.
 */
async function streamAudio(ws, response, conversationId, wsLog) {
  const audioUrl = response.metadata?.url;
  if (!audioUrl) {
    // No audio file available, send non-streaming response
    safeSend(ws, {
      type: "stream",
      conversationId,
      content: response.content,
      done: true,
      responseType: "audio",
      metadata: response.metadata,
    });
    return;
  }

  try {
    // Resolve file path from URL
    const filePath = path.join(__dirname, "..", "..", audioUrl.replace(/^\//, ""));

    try {
      await fsp.access(filePath);
    } catch {
      throw new Error("Generated audio file not found");
    }

    const { channels, sampleRate, bitsPerSample, pcmData, durationSec } = await parseWavFile(filePath);

    // Calculate chunk size in bytes
    const bytesPerSample = bitsPerSample / 8;
    const samplesPerChunk = Math.floor(sampleRate * AUDIO_CHUNK_DURATION_SEC);
    const bytesPerChunk = samplesPerChunk * channels * bytesPerSample;
    // parseWavFile rejects zero fmt fields, but a sample rate below
    // 1 / AUDIO_CHUNK_DURATION_SEC still floors samplesPerChunk to zero. A zero
    // chunk size makes totalChunks non-finite and the loop below never reaches
    // its last chunk, so it would emit empty frames forever without ever
    // sending done. Fail into the terminal fallback frame instead (Issue #362).
    if (!(bytesPerChunk > 0)) {
      throw new Error(`Unusable audio chunk size (sampleRate=${sampleRate}, channels=${channels}, bitsPerSample=${bitsPerSample})`);
    }

    const totalChunks = Math.ceil(pcmData.length / bytesPerChunk);

    // Send audio chunks
    for (let i = 0; i < totalChunks; i++) {
      if (ws.readyState !== 1 /* OPEN */) break;

      const start = i * bytesPerChunk;
      const end = Math.min(start + bytesPerChunk, pcmData.length);
      const chunk = pcmData.subarray(start, end);
      const isLast = i === totalChunks - 1;

      const message = {
        type: "stream",
        conversationId,
        content: i === 0 ? response.content : "",
        done: isLast,
        responseType: "audio",
        metadata: {
          chunk: i,
          totalChunks,
          chunkData: chunk.toString("base64"),
          sampleRate,
          channels,
          bitsPerSample,
          ...(isLast ? {
            url: audioUrl,
            model: response.metadata.model,
            durationSec,
          } : {}),
        },
      };

      const sent = safeSend(ws, message);

      // Small delay between chunks to simulate streaming and avoid overwhelming the client
      if (!sent || isLast) break;
      await new Promise(r => setTimeout(r, 50));
    }
  } catch (err) {
    wsLog.error("audio streaming failed", { error: err.message });
    // Fallback: send non-streaming response with URL
    safeSend(ws, {
      type: "stream",
      conversationId,
      content: response.content,
      done: true,
      responseType: "audio",
      metadata: response.metadata,
    });
  }
}

function setupWebSocket(wss) {
  wss.on("connection", (ws, req) => {
    const clientId = randomUUID();
    const wsLog = createLogger({ connectionId: clientId });
    // Resolve the client key using the same proxy-trust semantics as Express
    // req.ip so that REST and WebSocket requests from the same real client
    // share one rate-limit bucket.  Reading X-Forwarded-For directly (old
    // code) let a client forge the header to get a fresh bucket per frame.
    const clientKey = resolveClientIp(req, config.trustProxy) || clientId;
    wsLog.info("WebSocket client connected");

    // Track approval state per session
    let denyEverything = false;
    const pendingApprovals = new Map();

    const cleanupApprovals = () => {
      for (const respond of pendingApprovals.values()) {
        try {
          respond(false);
        } catch {
          // ignore
        }
      }
      pendingApprovals.clear();
    };

    ws.on("message", async (data) => {
      // Declared per message and outside the try so the catch-all below can
      // name the conversation a failed turn belonged to. It stays undefined
      // until parseChatFrame has validated an id, so a frame that fails
      // validation reports no id rather than echoing an unvalidated one
      // (Issue #358).
      let conversationId;

      try {
        const message = JSON.parse(data);

        if (message.type === "approval_response") {
          if (message.denyEverything) {
            denyEverything = true;
          }
          if (message.approvalId && pendingApprovals.has(message.approvalId)) {
            const respond = pendingApprovals.get(message.approvalId);
            pendingApprovals.delete(message.approvalId);
            respond(Boolean(message.approved));
          }
          return;
        }

        if (message.type === "chat") {
          const frame = parseChatFrame(message);
          // Known from here on, so a throw anywhere later in the turn still
          // reports which conversation it belonged to.
          conversationId = frame.conversationId;
          const { content, messageType, settings, attachments } = frame;

          // Shares buckets with the REST generation routes, so the limit
          // cannot be sidestepped by switching transport.
          if (generationCounter.enabled) {
            const { allowed, retryAfter } = generationCounter.hit(clientKey);
            if (!allowed) {
              safeSend(ws, {
                type: "error",
                conversationId,
                code: "RATE_LIMITED",
                message: `Too many generation requests. Try again in ${retryAfter}s.`,
              });
              return;
            }
          }

          // Send acknowledgment
          safeSend(ws, {
            type: "ack",
            messageId: randomUUID(),
            conversationId,
          });

          // Send typing indicator
          safeSend(ws, { type: "typing", conversationId });

          // Process and stream response
          // The turn joins the conversation the REST route records, so the
          // model sees the exchange rather than only its latest line. An
          // unknown id keeps the old single-turn behaviour.
          const userMessage = {
            role: "user",
            content,
            type: messageType,
            attachments,
            timestamp: new Date().toISOString(),
          };
          conversations.append(conversationId, userMessage);
          const recorded = conversations.messages(conversationId);
          const messages = recorded.length ? recorded : [userMessage];
          const operatorCtx = { operator: req?.headers?.["x-operator"] === "true" };
          const onApprovalRequest = ({ approvalId, command, argv, root, respond }) => {
            if (denyEverything) {
              respond(false);
              return;
            }
            pendingApprovals.set(approvalId, respond);
            const sent = safeSend(ws, {
              type: "approval_request",
              approvalId,
              conversationId,
              command,
              argv,
              root,
            });
            if (!sent) {
              pendingApprovals.delete(approvalId);
              respond(false);
            }
          };

          let streamedFromWorker = false;
          let accumulated = "";

          const onStream = (chunk) => {
            if (ws.readyState !== 1 /* OPEN */) return;
            if (chunk && chunk.delta) {
              streamedFromWorker = true;
              accumulated += chunk.delta;
              safeSend(ws, {
                type: "stream",
                conversationId,
                content: accumulated,
                done: false,
                responseType: "text",
              });
            }
          };

          const response = await model.processMessage(
            messages,
            messageType,
            settings,
            { onApprovalRequest, operatorCtx, onStream },
            operatorCtx
          );

          // modelChat hands the worker's result.content through verbatim, so it
          // is not guaranteed to be a string. Normalise it before the turn is
          // recorded: the stored message and both streaming paths below all
          // expect a string, and recording first meant a malformed reply was
          // persisted and only then failed on .split(). Falling back to what
          // already streamed keeps a partially streamed reply; when nothing
          // streamed, accumulated is "" (Issue #356).
          if (typeof response.content !== "string") {
            response.content = accumulated;
          }

          // The reply joins the conversation too. Recording only the user's
          // half would give the next turn a history of questions with no
          // answers, which reads worse than no history at all.
          conversations.append(conversationId, {
            role: "assistant",
            content: response.content,
            type: response.type,
            timestamp: new Date().toISOString(),
          });

          // Privacy: validate and strip trace from response if not allowed (defense in depth)
          if (response.metadata?.trace) {
            const validated = model.traceAllowed(operatorCtx) ? model.validateTrace(response.metadata.trace) : null;
            if (validated) {
              response.metadata.trace = validated;
            } else {
              delete response.metadata.trace;
            }
          }

          // Special handling for audio: stream PCM chunks
          if (response.type === "audio") {
            await streamAudio(ws, response, conversationId, wsLog);
            return;
          }

          if (streamedFromWorker) {
            safeSend(ws, {
              type: "stream",
              conversationId,
              content: response.content || accumulated,
              done: true,
              responseType: response.type,
              metadata: response.metadata,
            });
          } else {
            // Fallback: simulated streaming for mock mode or non-streamed worker responses
            const words = response.content.split(" ");
            // Group words so a long reply still arrives in at most
            // MAX_SIMULATED_FRAMES frames. A reply with no more words than that
            // is unchanged, one word per frame; a longer one carries several
            // words per frame instead of growing the wire traffic with the
            // square of the word count. The frames stay cumulative prefixes and
            // the last one is still the complete reply (Issue #364).
            const wordsPerFrame = Math.ceil(words.length / MAX_SIMULATED_FRAMES);
            const frameCount = Math.ceil(words.length / wordsPerFrame);
            let acc = "";

            for (let i = 0; i < frameCount; i++) {
              if (ws.readyState !== 1 /* OPEN */) break;

              const slice = words.slice(i * wordsPerFrame, (i + 1) * wordsPerFrame);
              acc += (i > 0 ? " " : "") + slice.join(" ");
              const isDone = i === frameCount - 1;
              const sent = safeSend(ws, {
                type: "stream",
                conversationId,
                content: acc,
                done: isDone,
                responseType: response.type,
                metadata: isDone ? response.metadata : undefined,
              });

              if (!sent || isDone) break;

              // Simulate token generation delay
              await new Promise((r) => setTimeout(r, 20 + Math.random() * 30));
            }
          }
        }

        if (message.type === "ping") {
          safeSend(ws, { type: "pong" });
        }
      } catch (err) {
        // conversationId is undefined when the frame failed before one was
        // validated. JSON.stringify drops undefined values, so that case sends
        // exactly the frame it always did rather than a fabricated id.
        safeSend(ws, { type: "error", conversationId, message: err.message });
      }
    });

    ws.on("close", () => {
      wsLog.info("WebSocket client disconnected");
      cleanupApprovals();
    });

    ws.on("error", () => {
      cleanupApprovals();
    });
  });
}

module.exports = { setupWebSocket, parseWavFile };
