/**
 * WebSocket service for real-time streaming responses.
 */

const { randomUUID } = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");
const { processMessage } = require("./model");
const { validateTrace } = require("./model");
const { generationCounter } = require("../middleware/limiters");
const config = require("../config");

const { validator } = require("../middleware/validate");
const { readSettings } = require("../generationSettings");

const MESSAGE_TYPES = ["text", "code", "image", "video", "audio"];
const MAX_MESSAGE_LENGTH = 8000;

// Audio chunk size: 0.5 seconds of 16-bit mono PCM
// This provides smooth incremental playback without excessive message overhead
const AUDIO_CHUNK_DURATION_SEC = 0.5;

/**
 * Validate an incoming chat frame the same way the REST route does, so a bad
 * frame gets a clear error instead of failing somewhere in the model service.
 */
function parseChatFrame(message) {
  const content = typeof message.content === "string" ? message.content.trim() : "";
  if (!content) throw new Error("content is required");
  if (content.length > MAX_MESSAGE_LENGTH) {
    throw new Error(`content must be at most ${MAX_MESSAGE_LENGTH} characters`);
  }

  const messageType = message.messageType || "text";
  if (!MESSAGE_TYPES.includes(messageType)) {
    throw new Error(`messageType must be one of: ${MESSAGE_TYPES.join(", ")}`);
  }

  // Same bounds as the REST routes. Out-of-range values are reported rather
  // than quietly clamped, so a client cannot think a setting took effect.
  const v = validator(message);
  const settings = readSettings(v);
  if (v.errors.length) {
    const [first] = v.errors;
    throw new Error(`${first.field} ${first.message}`);
  }

  return { content, messageType, settings, conversationId: message.conversationId };
}

/**
 * Parse a WAV file and extract PCM audio data with metadata.
 * Assumes mono 16-bit PCM format (the format generated by model/serve.py).
 */
function parseWavFile(filePath) {
  const buffer = fs.readFileSync(filePath);

  // Minimal WAV header parsing - we know the format from serve.py
  // RIFF header (12 bytes) + fmt chunk (24 bytes) + data chunk header (8 bytes) = 44 bytes
  if (buffer.length < 44) {
    throw new Error("WAV file too small");
  }

  // Verify RIFF header
  if (buffer.toString("ascii", 0, 4) !== "RIFF") {
    throw new Error("Not a valid WAV file");
  }

  // Read format details
  const channels = buffer.readUInt16LE(22);
  const sampleRate = buffer.readUInt32LE(24);
  const bitsPerSample = buffer.readUInt16LE(34);

  // Find data chunk (skip to byte 36, read "data" marker and size)
  const dataMarker = buffer.toString("ascii", 36, 40);
  if (dataMarker !== "data") {
    throw new Error("WAV data chunk not found");
  }

  const dataSize = buffer.readUInt32LE(40);
  const pcmData = buffer.subarray(44, 44 + dataSize);

  return {
    channels,
    sampleRate,
    bitsPerSample,
    pcmData,
    durationSec: pcmData.length / (sampleRate * channels * (bitsPerSample / 8)),
  };
}

/**
 * Stream audio in chunks over WebSocket.
 * Reads the generated WAV file, extracts PCM data, and sends it in time-based chunks.
 */
async function streamAudio(ws, response, conversationId) {
  const audioUrl = response.metadata?.url;
  if (!audioUrl) {
    // No audio file available, send non-streaming response
    ws.send(JSON.stringify({
      type: "stream",
      conversationId,
      content: response.content,
      done: true,
      responseType: "audio",
      metadata: response.metadata,
    }));
    return;
  }

  try {
    // Resolve file path from URL
    const filePath = path.join(__dirname, "..", "..", audioUrl.replace(/^\//, ""));

    if (!fs.existsSync(filePath)) {
      throw new Error("Generated audio file not found");
    }

    const { channels, sampleRate, bitsPerSample, pcmData, durationSec } = parseWavFile(filePath);

    // Calculate chunk size in bytes
    const bytesPerSample = bitsPerSample / 8;
    const samplesPerChunk = Math.floor(sampleRate * AUDIO_CHUNK_DURATION_SEC);
    const bytesPerChunk = samplesPerChunk * channels * bytesPerSample;

    const totalChunks = Math.ceil(pcmData.length / bytesPerChunk);

    // Send audio chunks
    for (let i = 0; i < totalChunks; i++) {
      const start = i * bytesPerChunk;
      const end = Math.min(start + bytesPerChunk, pcmData.length);
      const chunk = pcmData.subarray(start, end);
      const isLast = i === totalChunks - 1;

      const message = {
        type: "stream",
        conversationId,
        content: i === 0 ? response.content : "",
        done: isLast,
        responseType: "audio",
        metadata: {
          chunk: i,
          totalChunks,
          chunkData: chunk.toString("base64"),
          sampleRate,
          channels,
          bitsPerSample,
          ...(isLast ? {
            url: audioUrl,
            model: response.metadata.model,
            durationSec,
          } : {}),
        },
      };

      ws.send(JSON.stringify(message));

      // Small delay between chunks to simulate streaming and avoid overwhelming the client
      if (!isLast) {
        await new Promise(r => setTimeout(r, 50));
      }
    }
  } catch (err) {
    console.error("[websocket] audio streaming failed:", err.message);
    // Fallback: send non-streaming response with URL
    ws.send(JSON.stringify({
      type: "stream",
      conversationId,
      content: response.content,
      done: true,
      responseType: "audio",
      metadata: response.metadata,
    }));
  }
}

function setupWebSocket(wss) {
  wss.on("connection", (ws, req) => {
    const clientId = randomUUID();
    // Rate limit key. There is no Express request here, so read the socket
    // directly. The forwarded header is only honoured when a proxy is trusted,
    // otherwise a client could set it and get a fresh bucket per frame.
    const forwarded = config.trustProxy
      ? (req?.headers["x-forwarded-for"] || "").split(",")[0].trim()
      : "";
    const clientKey = forwarded || req?.socket?.remoteAddress || clientId;
    console.log(`WebSocket client connected: ${clientId}`);

    ws.on("message", async (data) => {
      try {
        const message = JSON.parse(data);

        if (message.type === "chat") {
          const { content, conversationId, messageType, settings } = parseChatFrame(message);

          // Shares buckets with the REST generation routes, so the limit
          // cannot be sidestepped by switching transport.
          if (generationCounter.enabled) {
            const { allowed, retryAfter } = generationCounter.hit(clientKey);
            if (!allowed) {
              ws.send(
                JSON.stringify({
                  type: "error",
                  conversationId,
                  code: "RATE_LIMITED",
                  message: `Too many generation requests. Try again in ${retryAfter}s.`,
                })
              );
              return;
            }
          }

          // Send acknowledgment
          ws.send(
            JSON.stringify({
              type: "ack",
              messageId: randomUUID(),
              conversationId,
            })
          );

          // Send typing indicator
          ws.send(JSON.stringify({ type: "typing", conversationId }));

          // Process and stream response
          const messages = [{ role: "user", content }];
          const operatorCtx = { operator: req?.headers?.["x-operator"] === "true" };
          const response = await processMessage(messages, messageType, settings, null, operatorCtx);

          // Privacy: validate and strip trace from response if not allowed (defense in depth)
          const traceAllowed = process.env.INCLUDE_TRACE === "true" || operatorCtx.operator === true;
          if (response.metadata?.trace) {
            if (traceAllowed) {
              const validated = validateTrace(response.metadata.trace);
              if (validated) {
                response.metadata.trace = validated;
              } else {
                delete response.metadata.trace;
              }
            } else {
              delete response.metadata.trace;
            }
          }

          // Special handling for audio: stream PCM chunks
          if (response.type === "audio") {
            await streamAudio(ws, response, conversationId);
            return;
          }

          // Normal text/code streaming by word-splitting
          const words = response.content.split(" ");
          let accumulated = "";

          for (let i = 0; i < words.length; i++) {
            accumulated += (i > 0 ? " " : "") + words[i];
            const isDone = i === words.length - 1;
            ws.send(
              JSON.stringify({
                type: "stream",
                conversationId,
                content: accumulated,
                done: isDone,
                responseType: response.type,
                metadata: isDone ? response.metadata : undefined,
              })
            );
            // Simulate token generation delay
            await new Promise((r) => setTimeout(r, 20 + Math.random() * 30));
          }
        }

        if (message.type === "ping") {
          ws.send(JSON.stringify({ type: "pong" }));
        }
      } catch (err) {
        ws.send(JSON.stringify({ type: "error", message: err.message }));
      }
    });

    ws.on("close", () => {
      console.log(`WebSocket client disconnected: ${clientId}`);
    });
  });
}

module.exports = { setupWebSocket };
